# Generated by Django 5.1.4 on 2025-01-07 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GeoLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                ("country", models.CharField(blank=True, max_length=60)),
                ("city", models.CharField(blank=True, max_length=60)),
                ("zip", models.CharField(blank=True, max_length=10)),
                (
                    "web_address",
                    models.CharField(
                        help_text="Web address or IP address. Start with a protocol (http:// or https://)",
                        max_length=255,
                        unique=True,
                    ),
                ),
            ],
        ),
    ]
